stages:
  split_data:
    cmd: python src/data/split_data.py data/raw.csv data/processed
    deps:
    - data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize_data:
    cmd: python src/data/normalize_data.py data/processed
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  hyperparameter_tuning:
    cmd: python src/models/grid_search.py data/processed models
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/models/train_model.py data/processed models/best_params.pkl models
    deps:
      - src/models/train_model.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/best_params.pkl
    outs:
      - models/trained_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py data/processed models/trained_model.pkl
      data metrics
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions.csv
    - metrics/scores.json
